/* Generated by tools/build-production.mjs. Publishable keys are safe for browser use. */
(function (global) {
  global.SENLOOP_CLOUD_CONFIG = Object.freeze({
  "url": "https://example.supabase.co",
  "publishableKey": "sb_publishable_qa_only_1234567890",
  "googleEnabled": false,
  "autoSync": true,
  "requestTimeoutMs": 12000
});
})(window);
